[package]
name = "sc-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
axum = { version = "0.8.9", features = ["ws"] }
clap = { version = "4.6.1", features = ["derive"] }
futures-util = "0.3.32"
rand = "0.10.2"
rfd = "0.17.2"
sc-core = { version = "0.1.0", path = "../../../../Core/shared/crates/sc-core" }
sc-domain = { version = "0.1.0", path = "../../../../Core/shared/crates/sc-domain" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "net", "signal"] }
tower-http = { version = "0.7.0", features = ["cors"] }
